[variables]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "development"

[phases.setup]
nixPkgs = ["nodejs_22", "npm"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]
dependsOn = ["install"]

[start]
cmd = "NODE_ENV=production npm run migrate && npm run start:prod"
